version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - "./.mysql:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "relay11db"
      MYSQL_USER: "relay11"
      MYSQL_PASSWORD: "123123"
      MYSQL_ROOT_PASSWORD: "root"
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8888:8080